### ISSUE TITLE
[Bug] LSPosed modules not showing in modules tab.

### ISSUE THREAD

**Issue by ProtoSharkk** [LSPosed/LSPosed#2638]
### Steps to reproduce/复现步骤

1. Install LSPosed zygisk
2. Install a few modules
3. Wait a couple of days

### Expected behaviour/预期行为

Opening the modules tab should display all of my active and inactive modules.

### Actual behaviour/实际行为

Modules don't display in modules tab, both in parasitic manager and LSPosed app. Modules that I had already enabled continued to work, but I couldn't enable or disable them anymore. After reinstalling any module on my phone the notification showed up saying "module not yet enabled" and it took me to the blank modules page. I tried to reinstall lsposed to fix it but all my modules got disabled and the issue persisted. The issue also continued after uninstalling all my magisk modules (including LSPosed) and then reinstalling just LSPosed.
![Screenshot_20230719-000342](https://github.com/LSPosed/LSPosed/assets/130694806/632178d2-a4da-4fb4-9c1b-2719ae41d2c3)

### Xposed Module List/Xposed 模块列表

```shell
AllTrans
AOSP Mods
Classic Power Menu
Iconify
UniversalAuth
```

### Magisk Module List/Magisk 模块列表

```shell
Advanced Charging Controller
Fullscreen/Immersive gestures
Hide Status Bar
Iconify
Universal SafetyNet Fix
Zygisk - LSPosed

(issue continued with all of these disabled)
```

### LSPosed version/LSPosed 版本

1.8.6 (6941)

### Android version/Android 版本

13 (TQ3A.230705.001), CalyxOS

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-07-19T00_25_27.574825.zip](https://github.com/LSPosed/LSPosed/files/12092216/LSPosed_2023-07-19T00_25_27.574825.zip)
[magisk_log_2023-07-19T00.26.23.log](https://github.com/LSPosed/LSPosed/files/12092224/magisk_log_2023-07-19T00.26.23.log)

**Comment by ProtoSharkk** [comment]
I switched to the latest dev build after I started experiencing the bug, but it started while using 1.8.6 (6712)

**Comment by yujincheng08** [comment]
You know what. There's a log saying the following error:
```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean org.lsposed.lspd.ILSPManagerClientService.refreshAppList(boolean)' on a null object reference
```

`refresshAppList` was from an unmerged PR: 

https://github.com/LSPosed/LSPosed/pull/2588/files#diff-49dfa657ae0108c2484b60c5176ebd080e8d5392ca3cae479c22ba2deb1f6edaR44

So this is not a valid report.

**Comment by ProtoSharkk** [comment]
Do you know how I can fix the problem? is there any way I can get a completely fresh install of LSPosed?

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/LSPosed/actions/workflows/core.yml?query=branch%3Amaster Use the last build here and grab log again.

**Comment by ProtoSharkk** [comment]
Do I use debug or release? I'm assuming debug.

**Comment by yujincheng08** [comment]
debug

**Comment by ProtoSharkk** [comment]
[LSPosed_2023-07-19T00_41_47.707251.zip](https://github.com/LSPosed/LSPosed/files/12092359/LSPosed_2023-07-19T00_41_47.707251.zip)
[magisk_log_2023-07-19T00.43.07.log](https://github.com/LSPosed/LSPosed/files/12092362/magisk_log_2023-07-19T00.43.07.log)

**Comment by yujincheng08** [comment]
> Wait a couple of days

Do you mean it wont happen after a fresh installation?

**Comment by ProtoSharkk** [comment]
I'm not sure. I've tried uninstalling and reinstalling the magisk module itself, but that didn't seem to fix the issue so I'm wondering if there's more I need to do to get a clean install.

**Comment by yujincheng08** [comment]
did it work on previous ver

**Comment by ProtoSharkk** [comment]
If by previous version, you mean the 1.8.6 from the main releases page, then it worked for a couple of days and then stopped working. I can't remember anything I might have done to trigger it, but after that point I couldn't get the modules to display in the modules tab even after reinstalling it and disabling all my other magisk modules.

**Comment by ProtoSharkk** [comment]
Closing the issue was a misclick, sorry.

**Comment by yupyee** [comment]
Yes, I can confirm this bug because the same issue happened to my device on android 13 with the latest "LSPosed-v1.8.6-6712-zygisk-release.zip". However, I might have found the actual bug itself. If the developers are interested, please read my case presented below.
- Bug seems to be caused by parallel-space-app such as Island in my case.
- LSPosed-v1.8.6's Module-tab might have failed to display both host-profile-space and work-profile-space at the same time, or   
  have loaded only work-profile-space (an empty module page). That's why previously installed modules are still active even though
  there is nothing under Module-tab. As a result, newly installed modules are not showing as well.
- (At least for me), completely removing work-profile-space including any cloned apps using in-app options provided by 
   parallel-space-app, or whatever ways to do so, then uninstall parallel-space-app and reboot fixes the issue.
- (or At least for me), instead install "LSPosed-v1.8.5-6649-zygisk-release.zip" which does not have the issue. It's working even with 
   the presence of parallel-space-app. The module-tab can display and toggle between host-profile-space and work-profile-space.

**Comment by yujincheng08** [comment]
@yupyee Could you specify the exact version that starts to fail?

**Comment by yupyee** [comment]
Already did. Android 13 with the latest "LSPosed-v1.8.6-6712-zygisk-release.zip".

**Comment by yujincheng08** [comment]
@yupyee so you imply 6712 fails but 6711 works?

**Comment by yupyee** [comment]
Yes. releases-1.8.5 works without issue.

**Comment by yujincheng08** [comment]
6711 -> 6712 only update readme. It must not be a problematic commit.

**Comment by yupyee** [comment]
I already tested my steps with "LSPosed-v1.8.6-6712-zygisk-release.zip": after removing parallel-space app including cloned apps altogether, the module-tab is working again.

**Comment by yujincheng08** [comment]
So? I want to find out the exact commit that causes the problem.

**Comment by yujincheng08** [comment]
So have you tested 6711?

**Comment by yupyee** [comment]
Yes, with parallel-space app installed: empty module page if  using "LSPosed-v1.8.6-6712-zygisk-release.zip".
Therefore, I tried just removing 1.8.6 and installed 1.8.5 instead. 1.8.5 works and has 2 tabs under Module-tab (host-profile and work-profile).

**Comment by yujincheng08** [comment]
@yupyee 1.8.5 is 6649, not 6711. Please try 6711. You are not following my instruction.

**Comment by yujincheng08** [comment]
@yupyee Github Action or our Telegram CI channel

**Comment by YeQi07** [comment]
I have this problem to.Wish the bug to be fixed sooner.

**Comment by YeQi07** [comment]
1.85-6649 really worked,and it also showed the “壶中界” on “炼妖壶”(insular).
![Screenshot_20230810-050708_Shell](https://github.com/LSPosed/LSPosed/assets/130123551/bec5a4a6-1df6-4591-8e58-0f0a17d41780)
(the red part is my name)

**Comment by olixu** [comment]
我也是遇到了同样的问题，降级版本到1.8.5可以解决该问题。

**Comment by zzColin** [comment]
The latest build (6981) does not have this bug. Maybe this issue can be closed?

More information:

6664 is the last build that did not have the "blank Modules page" issue. Starting from 6673 this issue can be reproduced with the Island app (work profile) configured.

My device is OnePlus 7 Pro with crDroid 9 (Android 13). My another device, OnePlus 3 with LineageOS 18.1 (Android 11) does not have this issue with build 6712.

**Comment by yujincheng08** [comment]
cool. can other guys confirm this was fixed on 6981 build?

**Comment by quantumfallout** [comment]
Build 6981 didn't solve the issue for me.
I'm using OnePlus 8t, Crdroid 9.8. Island version 6.1.2
With work profile created, the module tab went blank and destroying the work profile makes the issue gone.
Crdroid has built-in app cloning feature "Parallel Spaces" which has no issue with build 6981 and previous

**Comment by Howard20181** [comment]
> Build 6981 didn't solve the issue for me. I'm using OnePlus 8t, Crdroid 9.8. Island version 6.1.2 With work profile created, the module tab went blank and destroying the work profile the issue gone. Crdroid has built-in app cloning feature "Parallel Spaces" which has no issue with build 6981 and previous builds.

What's the Android version of yours system?

**Comment by quantumfallout** [comment]
> > Build 6981 didn't solve the issue for me. I'm using OnePlus 8t, Crdroid 9.8. Island version 6.1.2 With work profile created, the module tab went blank and destroying the work profile the issue gone. Crdroid has built-in app cloning feature "Parallel Spaces" which has no issue with build 6981 and previous builds.
> 
> What's the Android version of yours system?

Android 13
![Screenshot_20230827-195954_设置](https://github.com/LSPosed/LSPosed/assets/16105768/c1bb4e60-abdf-4da4-8740-b2963425ca41)

**Comment by Howard20181** [comment]
Try this build, added some logs
[LSPosed-v1.8.6-6985-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/12462785/LSPosed-v1.8.6-6985-zygisk-debug.zip)

**Comment by quantumfallout** [comment]
[LSPosed_2023-08-29T18_43_26.978798.zip](https://github.com/LSPosed/LSPosed/files/12463640/LSPosed_2023-08-29T18_43_26.978798.zip)


> Try this build, added some logs [LSPosed-v1.8.6-6985-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/12462785/LSPosed-v1.8.6-6985-zygisk-debug.zip)

**Comment by Howard20181** [comment]
Only the modules page went blank?

**Comment by quantumfallout** [comment]
The badges Repo tab has also gone missing.
![photo_2023-08-29_19-12-48](https://github.com/LSPosed/LSPosed/assets/16105768/963e85e7-6cef-488c-867e-cd9c6c4bb357)
![photo_2023-08-29_19-12-59](https://github.com/LSPosed/LSPosed/assets/16105768/06ddb555-4644-444e-9d11-74c354bbb5ad)

**Comment by Howard20181** [comment]
Use this to get some logs
[LSPosed-v1.8.6-6985-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/12464010/LSPosed-v1.8.6-6985-zygisk-debug.zip)

**Comment by quantumfallout** [comment]
> Use this to get some logs [LSPosed-v1.8.6-6985-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/12464010/LSPosed-v1.8.6-6985-zygisk-debug.zip)

Here
[LSPosed_2023-08-29T19_46_53.431881.zip](https://github.com/LSPosed/LSPosed/files/12464101/LSPosed_2023-08-29T19_46_53.431881.zip)

**Comment by Howard20181** [comment]
```
08-29 19:46:29.480 20453 20453 D LSPosedManager: onCreate: ModulesFragment
08-29 19:46:29.480 20453 20453 D LSPosedManager: onCreateView: ModulesFragment
08-29 19:46:29.494 20453 20453 E LSPosedManager: onModulesReloaded: users is null
```

**Comment by Howard20181** [comment]
I don't know why this happen, may be is your system's issue

**Comment by Howard20181** [comment]
Use this to get some logs
[LSPosed-v1.8.6-6986-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/12464266/LSPosed-v1.8.6-6986-zygisk-debug.zip)

**Comment by quantumfallout** [comment]
> Use this to get some logs [LSPosed-v1.8.6-6986-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/12464266/LSPosed-v1.8.6-6986-zygisk-debug.zip)


[LSPosed_2023-08-29T20_23_37.994058.zip](https://github.com/LSPosed/LSPosed/files/12464470/LSPosed_2023-08-29T20_23_37.994058.zip)

**Comment by Howard20181** [comment]
At this time, users are not null but the modules page is still blank?

**Comment by Howard20181** [comment]
UserHandle.getAppId(callingUid) == null for ROOT process, should fix in upstream.
https://github.com/crdroidandroid/android_frameworks_base/commit/a5f34cece47635fc761aa5e69c311c2270a3988b#diff-db3f1a87467b6d982c860052d857e80e5459731200d95eab6865d1b0928f39c9R1655

**Comment by aviraxp** [comment]
https://review.calyxos.org/c/CalyxOS/platform_frameworks_base/+/18785
